### ISSUE TITLE
Adjust Width on Window Resize

### ISSUE THREAD

**Issue by carstengrimm** [abelcabezaroman/definitive-image-comparison-slider#1]
I am quite happy with the comparison slider, however when i resize the browser window, the width in my container is not adjusting, resulting in either the slider getting too big (and overflow) or to small.

i have tried using 

```
    window.addEventListener('resize', function(event) {
        var container = document.querySelector('.b-dics');
        container.style.width = '100%'
    });
```

but that does not seem to do the job. Any help?

**Comment by abelcabezaroman** [comment]
Hello @carstengrimm sorry for late. I have read today your message!

I have added an update to library so now you don´t need to add nothing to get what you need. 

Automatically is resizing the comparison slider with this new feature.

I hope this help you! 😄
