### ISSUE TITLE
Question about dics loading

### ISSUE THREAD

**Issue by mli0603** [abelcabezaroman/definitive-image-comparison-slider#2]
Hi @abelcabezaroman 

Thank you for your great work. I wonder if it is possible to load the `dics` automatically instead of manually specifying the index. For example as shown in the code blow, the first `dics` with index 0 is specified.

https://github.com/abelcabezaroman/definitive-image-comparison-slider/blob/3f95617c08fdbf2e7f3e9eb0dd5c56f1fbf4f0c1/demo/index.html#L15-L18

Thank you!

**Comment by abelcabezaroman** [comment]
Yeah for sure!

"container" key only need a DOM node. If you insert an individual node it will works. Like this:

new Dics({ 
     container: document.querySelector('.example'), 
     textPosition: 'top' 
 });

If you want to do it automatically for all yours ".b-dics" class you will need to do a loop when page loads.
